[test_beam]
    name = "DESY March 2025"
    project_directory = "/home/etl/Test_Stand/ETL_TestingDAQ/"
    beam_energy = 120 # GeV

[run_config]
    comment = "Temperature -20C at new trigger threshold"
    num_runs = 200
    run_log_directory = "/home/etl/Test_Stand/ETL_TestingDAQ/Test_Beam_Data/DebugTB/run_logs"

[telescope_config]
    kcu_ip_address = "192.168.0.10"
    kcu_firmware_version = "abc123"
    l1a_delay = 14 # units ns??
    offset = 5 # vth
    power_mode = "high"
    etroc_binary_data_directory = "/home/etl/Test_Stand/ETL_TestingDAQ/Test_Beam_Data/DebugTB/etroc_binaries"

    [[telescope_config.service_hybrids]]
        telescope_layer = 'first'
        readout_board_name = "RB0015"
        rb = 0
        readout_board_version = "v2.2"
        readout_board_config = "modulev1"
        module_select = [[110], [], []]
        bias_voltage = 260

        #Optional
        LV_psu = "Siglent SPD3303X_E"
        HV_psu = "CAEN HV Power Supply"

    # [[telescope_config.service_hybrids]]
    #     telescope_layer = 'second'
    #    readout_board_name = "RB0034"
    #     rb = 1
    #     readout_board_version = "2.2"
    #     readout_board_config = "modulev1"
    #     module_select = [[], [111], []]
    #     bias_voltage = 260

    #     #Optional
    #     LV_psu = "Siglent SPD3303X_E"
    #     HV_psu = "CAEN HV Power Supply"

[oscilloscope]
    name = "Teledyne LeCroy Waverunner 8104"
    ip_address = "192.168.0.6"
    binary_data_directory = "/home/etl/Test_Stand/daq/LecroyMount/"
    sample_rate = [20, "GS/s"]
    horizontal_window = [25, "NS"]
    segment_display = "Overlay"
    sample_mode = "Sequence"
    number_of_segments = 5000

    [oscilloscope.channels.2]
        for = "MCP"
        coupling = 'D50'
        vertical_axis =  { min=-2, max=2, units="V" }
        trigger = {mode="NORM", condition="EDGE", slope="NEG", level=-0.2, units="V"}

    [oscilloscope.channels.3]
        for = "Clock"
        coupling = 'D50'
        vertical_axis = { min=-2, max=2, units="V" }

[watchdog]
    final_archive_directory = "/media/etl/Storage/DESY_April_2025/"
    monitor_directory = "/home/etl/Test_Stand/ETL_TestingDAQ/Test_Beam_Data/DebugTB/"

# Power Supplies
[[power_supplies]]
    name = "CAEN HV Power Supply"
    log_path = "/home/etl/CAENGECO2020.log"

#Optional Definitions of the LV powersupplies
[[power_supplies]]
    name = "Siglent SPD3303X-E"
    ip_address = "192.168.0.25"