export TAMALERO_BASE=$PWD/module_test_sw
export TEST_BEAM_BASE=$PWD
export LD_LIBRARY_PATH=/opt/cactus/lib:$LD_LIBRARY_PATH
export PYTHONPATH=$PYTHONPATH:$PWD
export PYTHONPATH=$PYTHONPATH:$TAMALERO_BASE
export PYTHONIOENCODING=utf8
echo "Set PYTHONPATH"
echo $PYTHONPATH
echo "Set LD_LIBRARY"
echo $LD_LIBRARY_PATH