
[test_beam]
    name = "DESY March 2025"
    beam_energy = 120 # GeV
    project_directory = "/home/etl/Test_Stand/ETL_TestingDAQ/"

[run_config]
    comment = "Temperature -20C at new trigger threshold"
    kcu_ip_address = "192.168.0.10"
    kcu_firmware_version = "abc123"
    num_events = 5000
    num_runs = 200

    # Global ETROC configurations
    etroc_binary_data_directory = "/home/etl/Test_Stand/ETL_TestingDAQ/Test_Beam_Data/DebugTB/etroc_binaries"
    l1a_delay = 14 # units ns??
    offset = 10 # vth
    power_mode = "i1"

[telescope_setup]
    # following the telescope_<name>.yaml format
    [[telescope_setup.service_hybrids]] 
        readout_board_name = 15
        readout_board_version = "2.2"
        module_config_name = "modulev1" # to select the right config in module_test_sw
        modules = [[110], [], []]

        # ETROC Parameters
        bias_voltage = 260 #V

        #Optional
        LV_psu = "Siglent SPD3303X_E"
        HV_psu = "CAEN HV Power Supply"

[oscilloscope]
    name = "Teledyne LeCroy Waverunner 8104"
    ip_address = "192.168.0.6"
    binary_data_directory = "/home/etl/Test_Stand/daq/"
    sample_rate = 20 # Gs/s
    horizontal_window = 50 # ns
    mcp_channel = "C2"
    clock_channel = "C3"
    trigger = -0.3 # V
    v_scale_2 = 0.2
    v_scale_3 = 0.2
    v_position_2 = 3
    v_position_3 = -3
    time_offset = 0
    trigger_slope = "NEG"

[file_processing]
    merged_data_directory = "/home/etl/Test_Stand/ETL_TestingDAQ/Test_Beam_Data/DebugTB/merged" # will add test beam name
    backup_directory = "/media/etl/Storage/"

# Power Supplies
[[power_supplies]]
    name = "CAEN HV Power Supply"
    log_path = "/home/etl/CAENGECO2020.log"

#Optional Definitions of the LV powersupplies
[[power_supplies]]
    name = "Siglent SPD3303X-E"
    ip_address = "192.168.0.25"
